server:
  port: 8090

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: msvc.users
          uri: lb://msvc.users
          predicates:
            - Path=/users/**
        - id: msvc-solicitudes
          uri: lb://msvc.solicitudes
          predicates:
            - Path=/solicitudes/**,/medicamentos/**
            
          # NO usamos StripPrefix porque el endpoint ya espera /solicitudes
          # Si usas StripPrefix=1, eliminarías la palabra "/solicitudes", lo que causaría un 404
          
    discovery:
      locator:
        enabled: true
        lower-case-service-id: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
