# Etapa 1: Build de la app Angular
FROM node:20 AS build
WORKDIR /app
COPY . .
RUN npm install && npm run build

# Etapa 2: Servir con nginx
FROM nginx:1.25
COPY --from=build /app/dist /usr/share/nginx/html
COPY ./nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
